### ISSUE TITLE
Build Error  

### ISSUE THREAD

**Issue by rayloi777** [nspitko/hlimgui#13]
❯ cd extension
❯ mkdir build
mkdir: build: File exists
❯ cd build
❯ cmake ..
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/rayloi/Documents/GitHub/hlimgui/extension/build
❯ cmake --build .
Consolidate compiler generated dependencies of target hlimgui.hdll
[  1%] Building CXX object CMakeFiles/hlimgui.hdll.dir/clipping.cpp.o
In file included from /Users/rayloi/Documents/GitHub/hlimgui/extension/clipping.cpp:1:
/Users/rayloi/Documents/GitHub/hlimgui/extension/utils.h:47:109: error: conditional expression is ambiguous; 'const ImVec2' can be converted to 'vimvec2 *' (aka 'HLT_ImVec2 *') and vice versa
inline ImVec2 getImVec2(vimvec2* vec2, const ImVec2& default_value = ImVec2(0, 0)) { return vec2 == nullptr ? default_value : vec2; }
                                                                                                            ^ ~~~~~~~~~~~~~   ~~~~
/Users/rayloi/Documents/GitHub/hlimgui/extension/utils.h:48:115: error: conditional expression is ambiguous; 'const ImVec4' can be converted to 'vimvec4 *' (aka 'HLT_ImVec4 *') and vice versa
inline ImVec4 getImVec4(vimvec4* vec4, const ImVec4& default_value = ImVec4(0, 0, 0, 0)) { return vec4 == nullptr ? default_value : vec4; }
                                                                                                                  ^ ~~~~~~~~~~~~~   ~~~~
2 errors generated.
make[2]: *** [CMakeFiles/hlimgui.hdll.dir/clipping.cpp.o] Error 1
make[1]: *** [CMakeFiles/hlimgui.hdll.dir/all] Error 2
make: *** [all] Error 2

**Comment by nspitko** [comment]
More information is needed here. What platform? Compiler? Version?

**Comment by rayloi777** [comment]
> More information is needed here. What platform? Compiler? Version?

Mac os X 12.4 , M1 Pro, 

❯ cd extension
❯ mkdir build
❯ cd build
❯ arch -x86_64 /usr/local/bin/cmake ..
-- The C compiler identification is AppleClang 13.1.6.13160021
-- The CXX compiler identification is AppleClang 13.1.6.13160021
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/rayloi/Documents/GitHub/hlimgui/extension/build
❯ arch -x86_64 /usr/local/bin/cmake --Build .
CMake Error: Unknown argument --Build
CMake Error: Run 'cmake --help' for all supported options.
❯ arch -x86_64 /usr/local/bin/cmake --build .
[  1%] Building CXX object CMakeFiles/hlimgui.hdll.dir/clipping.cpp.o
In file included from /Users/rayloi/Documents/GitHub/hlimgui/extension/clipping.cpp:1:
/Users/rayloi/Documents/GitHub/hlimgui/extension/utils.h:47:109: error: conditional expression is ambiguous; 'const ImVec2' can be converted to 'vimvec2 *' (aka 'HLT_ImVec2 *') and vice versa
inline ImVec2 getImVec2(vimvec2* vec2, const ImVec2& default_value = ImVec2(0, 0)) { return vec2 == nullptr ? default_value : vec2; }
                                                                                                            ^ ~~~~~~~~~~~~~   ~~~~
/Users/rayloi/Documents/GitHub/hlimgui/extension/utils.h:48:115: error: conditional expression is ambiguous; 'const ImVec4' can be converted to 'vimvec4 *' (aka 'HLT_ImVec4 *') and vice versa
inline ImVec4 getImVec4(vimvec4* vec4, const ImVec4& default_value = ImVec4(0, 0, 0, 0)) { return vec4 == nullptr ? default_value : vec4; }
                                                                                                                  ^ ~~~~~~~~~~~~~   ~~~~
2 errors generated.
make[2]: *** [CMakeFiles/hlimgui.hdll.dir/clipping.cpp.o] Error 1
make[1]: *** [CMakeFiles/hlimgui.hdll.dir/all] Error 2
make: *** [all] Error 2


Thanks
