### ISSUE TITLE
[Critical] Install with git broken by a missing submodule reference

### ISSUE THREAD

**Issue by mrpierrot** [nspitko/hlimgui#22]
Hi.

When I tried to install or update the lastest version of the lib with haxelib and git : the install failed with this message : 
```
Error: Could not clone Git repository.
Error: Command failed with error 1
```
In fact I found a broken submodule reference for imgui-node-editor
![image](https://github.com/nspitko/hlimgui/assets/2980742/cfcc07a0-c110-417c-ad1c-2865aae46f6a)
If you click on it there is a 404 error (https://github.com/nspitko/imgui-node-editor/tree/168a6c25464e73735f4544fcc8c5280374047602)

Currently the latest version is broken. 
If I install manually the lib at this following commit : #84eae09bbe6f2017b30d3336ac97193d235bef69 that works fine.

**Comment by nspitko** [comment]
The branch this was pointing to got merged, and thus deleted. Pointed back to master.

**Comment by mrpierrot** [comment]
Thank you ! It's nice !
